# Generated by Django 5.2.1 on 2025-07-21 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_initial"),
        ("users", "0004_rename_name_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="name",
        ),
    ]
