openapi: 3.0.3
info:
  title: Skill Tracker REST API
  version: 1.0.0
  description: Skill Tracker — это REST API приложение для отслеживания и прокачки
    персональных навыков (скиллов).
paths: {}
components: {}
