# Generated by Django 5.2.1 on 2025-06-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskattachment',
            name='file_url',
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='file_id',
            field=models.UUIDField(
                blank=True,
                help_text='UUID файла в файловом сервисе',
                null=True,
            ),
        ),
    ]
