# Generated by Django 5.2.1 on 2025-07-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_taskattachment_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskattachment',
            name='file_id',
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='file_url',
            field=models.URLField(
                blank=True, help_text='Ссылка на внешний файл', null=True
            ),
        ),
    ]
