# Generated by Django 5.2.4 on 2025-08-18 18:15

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_taskattachment_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=tasks.models.default_deadline),
        ),
    ]
