# Generated by Django 5.2.1 on 2025-05-28 19:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(3)
                        ],
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('unspecified', 'Неопределенный'),
                            ('programming', 'Программирование'),
                            ('design', 'Дизайн'),
                            ('marketing', 'Маркетинг'),
                            ('management', 'Менеджмент'),
                            ('writing', 'Копирайтинг'),
                            ('other', 'Другое'),
                        ],
                        default='unspecified',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
