name: GitHub Actions for the Skill-Tracker project
run-name: Skill-Tracker-Tests
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: fake-secret-key-for-ci
      POSTGRES_DB: default_db
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: default_password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: '5432'

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yaml up -d

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until docker exec skills_core_pg pg_isready -U $POSTGRES_USER; do
            sleep 1
          done

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run Tests
        run: |
          poetry run pytest
